//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokoBeDia.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProduct
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Stock { get; set; }
        public string Type { get; set; }
        public int Price { get; set; }
    }
}
