//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokoBeDia.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTransaction
    {
        public Nullable<int> UserID { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public string Payment_Type { get; set; }
        public string Product_Name { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Subtotal { get; set; }
    }
}
